# Generated by Django 5.2.3 on 2025-07-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to follow up', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='followed_up_at',
            field=models.DateTimeField(blank=True, help_text='When follow-up was completed', null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for follow-up'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_action_needed', 'No Action Needed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to follow up', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='followed_up_at',
            field=models.DateTimeField(blank=True, help_text='When follow-up was completed', null=True),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for follow-up'),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_action_needed', 'No Action Needed')], default='new', max_length=20),
        ),
    ]
