# Generated by Django 6.0 on 2026-01-01 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_refunded",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_balance_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_charge_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name="PaymentLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                            ("fee", "Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="CAD", max_length=10)),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_balance_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-processed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entry_type", "processed_at"],
                        name="payments_pa_entry_t_7ac519_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("entry_type", "charge"),
                            models.Q(("stripe_charge_id", ""), _negated=True),
                        ),
                        fields=("entry_type", "stripe_charge_id"),
                        name="unique_charge_entry_per_charge_id",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("entry_type", "refund"),
                            models.Q(("stripe_refund_id", ""), _negated=True),
                        ),
                        fields=("entry_type", "stripe_refund_id"),
                        name="unique_refund_entry_per_refund_id",
                    ),
                ],
            },
        ),
    ]
