# Generated by Django 6.0 on 2026-01-02 00:01

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_accounting_ledger"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=Q(amount_refunded__lte=F("amount_gross")),
                name="payment_refunded_lte_gross",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentledgerentry",
            constraint=models.CheckConstraint(
                condition=Q(entry_type__in=["charge", "refund", "fee"], amount__gte=0)
                | Q(entry_type="adjustment"),
                name="ledger_entry_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentledgerentry",
            constraint=models.CheckConstraint(
                condition=Q(entry_type="charge") & ~Q(stripe_charge_id="")
                | ~Q(entry_type="charge"),
                name="ledger_entry_charge_requires_stripe_charge_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentledgerentry",
            constraint=models.CheckConstraint(
                condition=Q(entry_type="refund") & ~Q(stripe_refund_id="")
                | ~Q(entry_type="refund"),
                name="ledger_entry_refund_requires_stripe_refund_id",
            ),
        ),
    ]
