# Generated by Django 5.2.3 on 2025-06-25 19:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="features",
            field=wagtail.fields.StreamField(
                [("feature", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Font Awesome icon class (e.g., 'fas fa-graduation-cap')"
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="features_title",
            field=models.CharField(
                default="Why Choose THINK eLearn",
                help_text="Title for the features section",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Page to link to from the CTA button",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                default="Get Started",
                help_text="Text for the primary call-to-action button",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Hero background or featured image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True, help_text="Subtitle text below the main headline"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Empowering Learning Through Innovation",
                help_text="Main headline for the hero section",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="recent_posts_count",
            field=models.IntegerField(
                default=3, help_text="Number of recent posts to display"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="recent_posts_title",
            field=models.CharField(
                default="Latest Insights",
                help_text="Title for the recent posts section",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_recent_posts",
            field=models.BooleanField(
                default=True, help_text="Show recent blog posts on the homepage"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials",
            field=wagtail.fields.StreamField(
                [("testimonial", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.TextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0), ("author", 1), ("company", 2), ("avatar", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_title",
            field=models.CharField(
                default="What Our Clients Say",
                help_text="Title for the testimonials section",
                max_length=255,
            ),
        ),
    ]
