# Generated by Django 5.2.3 on 2025-06-26 03:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_features_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="About THINK eLearn",
                        help_text="Main headline for the about page",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True, help_text="Subtitle text below the main headline"
                    ),
                ),
                (
                    "story_title",
                    models.CharField(
                        default="Our Story",
                        help_text="Title for the company story section",
                        max_length=255,
                    ),
                ),
                (
                    "story_content",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Rich text content about the company story",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(
                        default="Our Mission",
                        help_text="Title for the mission section",
                        max_length=255,
                    ),
                ),
                (
                    "mission_content",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Rich text content about the company mission",
                    ),
                ),
                (
                    "values_title",
                    models.CharField(
                        default="Our Values",
                        help_text="Title for the values section",
                        max_length=255,
                    ),
                ),
                (
                    "values",
                    wagtail.fields.StreamField(
                        [("value", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Font Awesome icon class (e.g., 'fas fa-heart')"
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 0), ("title", 1), ("description", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "team_title",
                    models.CharField(
                        default="Meet Our Team",
                        help_text="Title for the team section",
                        max_length=255,
                    ),
                ),
                (
                    "team_members",
                    wagtail.fields.StreamField(
                        [("member", 6)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            1: ("wagtail.blocks.TextBlock", (), {}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "LinkedIn profile URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Twitter profile URL", "required": False},
                            ),
                            5: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("role", 0),
                                        ("bio", 1),
                                        ("photo", 2),
                                        ("linkedin", 3),
                                        ("twitter", 4),
                                        ("email", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "timeline_title",
                    models.CharField(
                        default="Our Journey",
                        help_text="Title for the timeline section",
                        max_length=255,
                    ),
                ),
                (
                    "milestones",
                    wagtail.fields.StreamField(
                        [("milestone", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Year (e.g., '2020')", "max_length": 4},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("year", 0), ("title", 1), ("description", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hero background or team image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
