# Generated by Django 5.2.3 on 2025-06-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_portfolioindexpage_projectcategory_projectpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="features_description",
            field=models.TextField(
                default="Discover what makes THINK eLearn the perfect partner for your educational technology needs.",
                help_text="Description text for the features section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="recent_posts_description",
            field=models.TextField(
                default="Stay informed with our latest articles on educational technology, learning methodologies, and industry insights.",
                help_text="Description text for the recent posts section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_description",
            field=models.TextField(
                default="See what our clients have to say about their experience working with us.",
                help_text="Description text for the testimonials section",
            ),
        ),
    ]
