# Generated by Django 5.2.3 on 2025-08-02 19:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_features_description_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='THINK eLearn Process', help_text='Main headline for the process page', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subtitle text below the main headline')),
                ('process_title', models.CharField(default='Our Process', help_text='Title for the process section', max_length=255)),
                ('process_content', wagtail.fields.RichTextField(blank=True, help_text='Rich text content about the company process')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero background', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Process Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
