# Generated by Django 5.2.4 on 2025-08-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_processpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioIndexPage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
