# Generated by Django 5.2.4 on 2025-08-04 01:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_portfolio_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processpage",
            name="process_content",
        ),
        migrations.RemoveField(
            model_name="processpage",
            name="process_title",
        ),
        migrations.AddField(
            model_name="processpage",
            name="process_sections",
            field=wagtail.fields.StreamField(
                [("process", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Process section title", "max_length": 255},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Process description"},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                },
                help_text="Add multiple process sections as needed",
            ),
        ),
    ]
