# Generated by Django 5.2.3 on 2025-08-09 23:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_processpage_process_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpage',
            name='process_sections',
            field=wagtail.fields.StreamField([('process', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Process section title', 'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Process description'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'fas fa-sync-alt', 'help_text': "FontAwesome icon class (e.g., 'fas fa-sync-alt', 'fas fa-rocket', 'fas fa-lightbulb')", 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('icon', 2)]], {})}, help_text='Add multiple process sections as needed'),
        ),
    ]
