# Generated by Django 5.2.9 on 2025-12-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_processpage_process_sections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessPage',
        ),
    ]
