# Generated by Django 5.2.9 on 2025-12-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursereview",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Approve this review to make it visible to other users",
            ),
        ),
    ]
