# Generated by Django 5.2.9 on 2025-12-29 22:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_coursereview_is_approved'),
        ('wagtail_lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('fixed', 'Fixed Price'), ('pwyc', 'Pay What You Can')], default='pwyc', help_text='Pricing model for this course', max_length=20)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, help_text="Fixed price (used when pricing_type='fixed')", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('suggested_price', models.DecimalField(decimal_places=2, default=0, help_text='Suggested PWYC amount (display only)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Minimum PWYC amount (0 to allow free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.DecimalField(decimal_places=2, default=1000, help_text='Maximum PWYC amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar')], default='CAD', help_text='Currency for pricing (CAD for launch)', max_length=3)),
                ('refund_window_days', models.IntegerField(default=30, help_text='Number of days customers can request refunds', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product can be purchased or enrolled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Product',
                'verbose_name_plural': 'Course Products',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount paid (0 for free enrollments)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, help_text='Prevents duplicate enrollments', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Record',
                'verbose_name_plural': 'Enrollment Records',
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user_review'),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='lms.extendedcoursepage'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='course_enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_record', to='wagtail_lms.courseenrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.courseproduct'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollmentrecord',
            index=models.Index(fields=['status', 'created_at'], name='lms_enrollm_status_d30deb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrecord',
            index=models.Index(fields=['user', 'status'], name='lms_enrollm_user_id_7dad22_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_enrolment'),
        ),
    ]
