# Generated by Django 6.0 on 2026-01-02 00:00

from django.core.validators import MinValueValidator
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_courseproduct_enrollmentrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseproduct",
            name="max_refunds_per_user",
            field=models.IntegerField(
                default=1,
                help_text="Maximum refunds/cancellations allowed per user for this product",
                validators=[MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrecord",
            name="has_refund",
            field=models.BooleanField(
                default=False,
                help_text="True if any refund was processed for this enrollment",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="enrollmentrecord",
            name="unique_user_product_enrolment",
        ),
        migrations.AddConstraint(
            model_name="enrollmentrecord",
            constraint=models.UniqueConstraint(
                condition=Q(status__in=["pending_payment", "active"]),
                fields=("user", "product"),
                name="unique_active_or_pending_enrollment",
            ),
        ),
    ]
