# Generated by Django 5.2.9 on 2025-12-29 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_courseproduct_enrollmentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for the course (0 for free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentrecord',
            name='pay_what_you_can_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional pay-what-you-can amount (0 for free enrollments)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
