# Generated by Django 6.0 on 2026-01-02 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_refund_limits_and_reenroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproduct',
            name='refund_window_days',
            field=models.IntegerField(default=30, help_text='Number of days customers can request refunds (max 365 days)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
