# Generated by Django 5.2.9 on 2025-12-29 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_add_field_validators'),
        ('wagtail_lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user_review'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_enrollment'),
        ),
    ]
