# Generated by Django 5.2.9 on 2025-12-29 04:05

import uuid

import django.core.validators
from django.db import migrations, models


def update_pricing_and_statuses(apps, schema_editor):
    CourseProduct = apps.get_model("lms", "CourseProduct")
    EnrollmentRecord = apps.get_model("lms", "EnrollmentRecord")

    CourseProduct.objects.filter(fixed_price__gt=0).update(pricing_type="fixed")
    CourseProduct.objects.filter(fixed_price=0).update(pricing_type="free")

    EnrollmentRecord.objects.filter(status="cancelled_refunded").update(
        status="refunded"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_use_unique_constraints"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseproduct",
            old_name="base_price",
            new_name="fixed_price",
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("fixed", "Fixed Price"),
                    ("pwyc", "Pay What You Can"),
                ],
                default="pwyc",
                help_text="Pricing model for this course",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="suggested_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Suggested PWYC amount (display only)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum PWYC amount (0 to allow free)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Maximum PWYC amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="currency",
            field=models.CharField(
                choices=[("CAD", "Canadian Dollar")],
                default="CAD",
                help_text="Currency for pricing (CAD for launch)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="courseproduct",
            name="refund_window_days",
            field=models.IntegerField(
                default=30,
                help_text="Number of days customers can request refunds",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="courseproduct",
            name="fixed_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed price (used when pricing_type='fixed')",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="pay_what_you_can_amount",
            new_name="amount_paid",
        ),
        migrations.AlterField(
            model_name="enrollmentrecord",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Actual amount paid (0 for free enrollments)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("active", "Active"),
                    ("payment_failed", "Payment Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrecord",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="enrollmentrecord",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="enrollmentrecord",
            name="idempotency_key",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Prevents duplicate enrollments",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="enrollmentrecord",
            name="unique_user_product_enrollment",
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentrecord",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="enrollmentrecord",
            index=models.Index(fields=["status", "created_at"], name="lms_enrollm_status_8a9ed3_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollmentrecord",
            index=models.Index(fields=["user", "status"], name="lms_enrollm_user_id_1b4e0d_idx"),
        ),
        migrations.RunPython(update_pricing_and_statuses, migrations.RunPython.noop),
    ]
