# Generated by Django 6.0.2 on 2026-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_courseproduct_refund_window_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedcoursepage',
            old_name='duration_hours',
            new_name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='extendedcoursepage',
            name='duration_minutes',
            field=models.PositiveIntegerField(
                blank=True, help_text='Estimated duration in minutes', null=True
            ),
        ),
    ]
