# Generated by Django 6.0.2 on 2026-03-05 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_rename_duration_hours_to_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedcoursepage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — listed in the catalogue'), ('unlisted', 'Unlisted — accessible by direct URL, not listed'), ('private_demo', 'Private Demo — client invite only')], default='public', help_text='Public: listed in the catalogue. Unlisted: accessible by direct URL but not listed. Private Demo: hidden from the catalogue; access via Client Demo Invite only.', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientDemoInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('demo_courses', models.ManyToManyField(blank=True, help_text='Courses included in this demo (private and/or public).', related_name='demo_invites', to='lms.extendedcoursepage')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDemoEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoke_on_expiry', models.BooleanField(default=True, help_text='False when the user was already enrolled before this invite was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_enrollments', to='lms.extendedcoursepage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_enrollments', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_enrollments', to='lms.clientdemoinvite')),
            ],
            options={
                'unique_together': {('invite', 'user', 'course')},
            },
        ),
    ]
