# Generated by Django 6.1 on 2026-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_extendedcoursepage_visibility_clientdemoinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedcoursepage',
            name='target_audience',
            field=models.CharField(choices=[('adults', 'Adults'), ('children', 'Children')], default='adults', help_text="Select the presentation best suited to this course's learners.", max_length=20),
        ),
    ]
