# Generated by Django 5.2.3 on 2025-08-09 21:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-graduation-cap')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the portfolio section')),
                ('hero_title', models.CharField(default='Our Portfolio', help_text='Main headline for the portfolio page', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subtitle text below the main headline')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Portfolio Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Creation date')),
                ('intro', models.CharField(help_text='Brief introduction/summary', max_length=250)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Detailed description')),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated list of technologies/tools used')),
                ('content_sections', wagtail.fields.StreamField([('packaged_content', 4), ('video_content', 11), ('gallery_content', 18), ('interactive_content', 23), ('text_content', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this content package', 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the content', 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'ZIP file containing the learning module'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Preview image for the content', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('package_file', 2), ('thumbnail', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this video', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the video', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('embed', 'YouTube/Vimeo Embed'), ('upload', 'Uploaded Video File')]}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube or Vimeo URL', 'required': False}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Uploaded video file', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Custom thumbnail image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('video_type', 7), ('embed_url', 8), ('video_file', 9), ('thumbnail', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this gallery', 'max_length': 100}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the gallery', 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('image', 14), ('caption', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 12), ('description', 13), ('images', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this content', 'max_length': 100}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Interactive content file (animation, PDF, etc.)'}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('download', 'Download Link Only'), ('embed', 'Embed/Display Inline'), ('iframe', 'Display in Frame')]}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Preview image', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('description', 1), ('content_file', 20), ('display_type', 21), ('thumbnail', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 25: ('wagtail.blocks.RichTextBlock', (), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 24), ('content', 25)]], {'icon': 'doc-full', 'label': 'Text Content'})}, help_text='Add different types of content to showcase your work')),
                ('target_audience', models.TextField(blank=True, help_text='Who is this content designed for?')),
                ('learning_objectives', models.TextField(blank=True, help_text='What will users learn or achieve?')),
                ('duration', models.CharField(blank=True, help_text="Estimated time to complete (e.g., '15 minutes', '2 hours')", max_length=50)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='portfolio.portfoliocategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main featured image for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
