# Generated by Django 5.2.4 on 2025-08-03 22:25

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Project Categories",
            },
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "project_date",
                    models.DateField(verbose_name="Project completion date"),
                ),
                ("client_name", models.CharField(blank=True, max_length=200)),
                (
                    "project_url",
                    models.URLField(blank=True, help_text="Live project URL"),
                ),
                ("intro", models.CharField(max_length=250)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "technologies",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of technologies used",
                    ),
                ),
                (
                    "results_title",
                    models.CharField(
                        default="Results & Impact",
                        help_text="Title for the results section",
                        max_length=255,
                    ),
                ),
                (
                    "results",
                    wagtail.fields.StreamField(
                        [("metric", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                            2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("value", 1), ("description", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "challenge_title",
                    models.CharField(
                        default="The Challenge",
                        help_text="Title for the challenge section",
                        max_length=255,
                    ),
                ),
                ("challenge_content", wagtail.fields.RichTextField(blank=True)),
                (
                    "solution_title",
                    models.CharField(
                        default="Our Solution",
                        help_text="Title for the solution section",
                        max_length=255,
                    ),
                ),
                ("solution_content", wagtail.fields.RichTextField(blank=True)),
                ("testimonial_quote", models.TextField(blank=True)),
                ("testimonial_author", models.CharField(blank=True, max_length=100)),
                ("testimonial_company", models.CharField(blank=True, max_length=100)),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="portfolio.projectcategory"
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "testimonial_avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
