# Generated by Django 5.2.3 on 2025-08-02 22:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepage',
            name='content_sections',
            field=wagtail.fields.StreamField([('packaged_content', 4), ('video_content', 11), ('gallery_content', 18), ('interactive_content', 23), ('text_content', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this content package', 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the content', 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'ZIP file containing the learning module'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Preview image for the content', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('package_file', 2), ('thumbnail', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this video', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the video', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('embed', 'YouTube/Vimeo Embed'), ('upload', 'Uploaded Video File')]}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube or Vimeo URL', 'required': False}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Uploaded video file', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Custom thumbnail image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('video_type', 7), ('embed_url', 8), ('video_file', 9), ('thumbnail', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this gallery', 'max_length': 100}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description of the gallery', 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('image', 14), ('caption', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 12), ('description', 13), ('images', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this content', 'max_length': 100}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Interactive content file (animation, PDF, etc.)'}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('download', 'Download Link Only'), ('embed', 'Embed/Display Inline'), ('iframe', 'Display in Frame')]}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Preview image', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('description', 1), ('content_file', 20), ('display_type', 21), ('thumbnail', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 25: ('wagtail.blocks.RichTextBlock', (), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 24), ('content', 25)]], {'icon': 'doc-full', 'label': 'Text Content'})}, help_text='Add different types of content to showcase your work'),
        ),
    ]
