# Generated by Django 5.2.4 on 2025-08-03 23:22

from django.db import migrations


def cleanup_and_create_portfolio(apps, schema_editor):
    """
    Clean up corrupted portfolio page and stale content types.
    Use setup_portfolio command to create the new page after this migration.
    """
    Page = apps.get_model('wagtailcore', 'Page')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        # 1. Delete the corrupted portfolio page if it exists
        try:
            corrupted_portfolio = Page.objects.get(slug='portfolio')
            print(f"Deleting corrupted portfolio page: {corrupted_portfolio.title}")
            corrupted_portfolio.delete()
        except Page.DoesNotExist:
            print("No existing portfolio page found")
        
        # 2. Remove stale content types for old portfolio models
        stale_content_types = ContentType.objects.filter(
            app_label='home',
            model__in=['portfolioindexpage', 'projectpage', 'projectcategory']
        )
        stale_count = stale_content_types.count()
        if stale_count > 0:
            print(f"Removing {stale_count} stale content types")
            stale_content_types.delete()
        
        print("✅ Cleanup complete. Run 'python manage.py setup_portfolio' to create the portfolio page.")
            
    except Exception as e:
        print(f"Error during portfolio cleanup: {e}")
        # Don't fail the migration
        

def reverse_cleanup_portfolio(apps, schema_editor):
    """
    Reverse the cleanup - just delete the portfolio page
    """
    PortfolioIndexPage = apps.get_model('portfolio', 'PortfolioIndexPage')
    
    try:
        portfolio_page = PortfolioIndexPage.objects.get(slug='portfolio')
        portfolio_page.delete()
        print("Removed portfolio page")
    except PortfolioIndexPage.DoesNotExist:
        print("No portfolio page to remove")
    except Exception as e:
        print(f"Error during portfolio cleanup rollback: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("home", "0009_remove_portfolio_models"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_and_create_portfolio,
            reverse_cleanup_portfolio,
        ),
    ]
