# Generated by Django 5.2.3 on 2025-08-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the client (for client work projects only)', max_length=200),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='is_client_work',
            field=models.BooleanField(default=False, help_text='Check if this project represents work done for a specific client'),
        ),
    ]
