# Generated by Django 5.2.6 on 2025-10-17 01:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="content_sections",
            field=wagtail.fields.StreamField(
                [
                    ("packaged_content", 4),
                    ("video_content", 12),
                    ("gallery_content", 19),
                    ("interactive_content", 24),
                    ("text_content", 27),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title for this content package",
                            "max_length": 100,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of the content",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "ZIP file containing the learning module"},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Preview image for the content",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("package_file", 2),
                                ("thumbnail", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this video", "max_length": 100},
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of the video",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("embed", "YouTube/Vimeo Embed"),
                                ("upload", "Uploaded Video File"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "YouTube or Vimeo URL", "required": False},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Uploaded video file", "required": False},
                    ),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Custom thumbnail image", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("16:9", "Horizontal (16:9 - Standard YouTube)"),
                                (
                                    "9:16",
                                    "Vertical (9:16 - YouTube Shorts, TikTok, Reels)",
                                ),
                            ],
                            "help_text": "Choose the video's aspect ratio for proper display",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("description", 6),
                                ("video_type", 7),
                                ("embed_url", 8),
                                ("video_file", 9),
                                ("thumbnail", 10),
                                ("aspect_ratio", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this gallery", "max_length": 100},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of the gallery",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("caption", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("description", 14), ("images", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this content", "max_length": 100},
                    ),
                    21: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Interactive content file (animation, PDF, etc.)"
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("download", "Download Link Only"),
                                ("embed", "Embed/Display Inline"),
                                ("iframe", "Display in Frame"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Preview image", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 20),
                                ("description", 1),
                                ("content_file", 21),
                                ("display_type", 22),
                                ("thumbnail", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    26: ("wagtail.blocks.RichTextBlock", (), {}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 25), ("content", 26)]],
                        {"icon": "doc-full", "label": "Text Content"},
                    ),
                },
                help_text="Add different types of content to showcase your work",
            ),
        ),
    ]
