"""Custom storage backends for S3-compatible services.

This module provides helpers and a storage backend subclass that make object
URLs generated by S3-compatible services (such as MinIO or private AWS S3
endpoints) usable directly in a browser.

In many deployments the internal S3 endpoint used by the application server
is not the same as the public-facing URL that browser clients should use.
The :func:`rewrite_s3_url` helper rewrites URLs that point at the internal
endpoint so they instead use a configured public base URL, while leaving all
other URLs untouched.

The :class:`BrowserAccessibleS3Storage` class extends
:class:`storages.backends.s3boto3.S3Boto3Storage` to automatically apply
this URL rewriting whenever a file URL is generated, allowing the application
to talk to an internal S3-compatible service while still returning
browser-accessible URLs to clients.

NOTE: BrowserAccessibleS3Storage is for dev only (Docker/MinIO URL rewriting).
Do NOT use in production.
"""

from __future__ import annotations

from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage


def rewrite_s3_url(
    url: str,
    endpoint_url: str | None,
    public_url: str | None,
) -> str:
    """Rewrite an internal S3 endpoint URL to a browser-accessible URL.

    Replaces the configured internal S3 endpoint prefix in ``url`` with a
    public base URL suitable for use by browser clients. If either
    ``endpoint_url`` or ``public_url`` is not provided, or if ``url`` does
    not start with the internal endpoint prefix, the original ``url`` is
    returned unchanged.

    Args:
        url: The absolute URL generated by the S3 storage backend, typically
            based on the internal S3 endpoint configuration.
        endpoint_url: The internal S3 endpoint base URL (e.g.
            ``http://minio:9000``) that should be rewritten when it appears
            as the leading part of ``url``. Trailing slashes are stripped
            before comparison. If ``None`` or empty, no rewriting is
            performed.
        public_url: The public or browser-accessible base URL that should
            replace the internal endpoint prefix (e.g.
            ``http://localhost:9000``). Trailing slashes are stripped before
            substitution. If ``None`` or empty, no rewriting is performed.

    Returns:
        The rewritten URL using the public base URL if ``url`` starts with
        ``endpoint_url`` and both values are provided; otherwise, the
        original ``url``.
    """
    if not endpoint_url or not public_url:
        return url

    endpoint = endpoint_url.rstrip("/")
    public = public_url.rstrip("/")
    if url.startswith(endpoint):
        return f"{public}{url[len(endpoint) :]}"
    return url


class BrowserAccessibleS3Storage(S3Boto3Storage):
    """S3 storage backend that rewrites internal endpoint URLs for browser access.

    Extends :class:`storages.backends.s3boto3.S3Boto3Storage` and
    post-processes the URL returned by
    :meth:`~storages.backends.s3boto3.S3Boto3Storage.url` to make it
    reachable by browser clients when the application communicates with S3
    through an internal endpoint that is not directly accessible from the
    browser (e.g. a Docker-internal MinIO hostname).

    URL rewriting is performed by :func:`rewrite_s3_url` and is controlled
    by the following Django settings:

    * ``AWS_S3_ENDPOINT_URL``: The internal S3-compatible endpoint used by
      django-storages for generating object URLs (e.g. ``http://minio:9000``
      inside a Docker network).
    * ``AWS_S3_BROWSER_ENDPOINT_URL``: The public base URL exposed to browser
      clients (e.g. ``http://localhost:9000``). When set, this replaces the
      ``AWS_S3_ENDPOINT_URL`` prefix in generated URLs so that links in pages
      and emails point to a browser-accessible location.

    Rewriting only occurs when both settings are non-empty and the generated
    URL begins with the internal endpoint. In all other cases the original URL
    from :class:`S3Boto3Storage` is returned unchanged.
    """

    def url(
        self,
        name: str,
        parameters: dict[str, str] | None = None,
        expire: int | None = None,
        http_method: str | None = None,
    ) -> str:
        url = super().url(
            name,
            parameters=parameters,
            expire=expire,
            http_method=http_method,
        )
        return rewrite_s3_url(
            url,
            getattr(settings, "AWS_S3_ENDPOINT_URL", None),
            getattr(settings, "AWS_S3_BROWSER_ENDPOINT_URL", None),
        )
